### ISSUE TITLE
Using the client without a server

### ISSUE THREAD

**Issue by paul90** [fedwiki/wiki-client#123]
In fedwiki/wiki-node-server#99 @opn askes:

>I'd like to be able to do a test of a pure javascript client running from a local file system without a server - or just a plain vanilla http server - how far away are we from being able to do this?

**Comment by paul90** [comment]
There was some work nearly 4 years ago looking at providing a 'static site' version. See WardCunningham/Smallest-Federated-Wiki#43.

**Comment by WardCunningham** [comment]
There are cross-origin resource sharing problems when accessing page with file: protocol.

**Comment by opn** [comment]
So I've done some research. First we need and can run a small local server to present the Fedwiki files via an http interface. The local server will need to serve the appropriate CORS headers. The IPFS daemon does this already I believe.

Second I'd like to define what the minimum server requirements are for a server to serve Fedwiki contnet to a client. That means assuming a browser or other native client has all it needs to deal with the content, what is required by the server to serve content for read / display purposes only?

I'd like to do this in a nice flexible way moving forwards - so that different server implementations are able to keep in sync. My thought on this is to define, implement and document a simple REST API using DreamFactory to implement and then document the API with [Swagger](http://swagger.io/). This generates a [standard markup](https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md) (an alternative would be [RAML](https://en.wikipedia.org/wiki/RAML_%28software%29#Example)).

In plain language it seems to me that the only thing the server truly needs to do is:
  1. Serve page json from a url of the form - http://example.com/some-page-slug.json?random=a_random-String
  1. Serve up a site map at a url of the form - http://example.com/system/sitemap.json
  1. Return the above content with a CORS wildcard header (Access-Control-Allow-Origin: *)
What else?

I get the following headers returned by the current wiki-node server:
```
HTTP/1.1 200 OK
X-Powered-By: Express
Access-Control-Allow-Origin: *
Accept-Ranges: bytes
Date: Sun, 28 Jun 2015 11:58:27 GMT
Cache-Control: public, max-age=0
Last-Modified: Sun, 28 Jun 2015 11:51:39 GMT
ETag: W/"1ed4-1959657124"
Content-Type: application/json
Content-Length: 7892
Connection: keep-alive
```
So my starting point is to define the REST API endpoint that everything a client needs to render pages. Later we can add POST, and PUT end points etc.

**Comment by WardCunningham** [comment]
Sites vary in how much service they provide. I will distinguish three cases, participating in the federation, originating access to the federation, and interactively creating content for the federation. The Wikiduino implementation, for example, provides only the most elementary service.

# Federation
To be read from a link a site must serve:
```
http://example.com/(slug).json
http://example.com/favicon.png
```
To be searched a site must serve:
```
http://example.com/system/sitemap.json
```
To be relocated a site should serve:
```
http://example.com/system/export.json
```
# Origin
To be read as an origin a site must serve:
```
http://example.com/
http://example.com/(slug).html
(plus all related html, css, core javascript)
```
To support the browser back button and lineup urls a site must serve:
```
http://example.com/(site/slug/site/slug ...)
```
To support non-core plugins a site must serve:
```
http://example.com/system/factories.json
http://example.com/system/plugins.json
http://example.com/plugins/(plugin)/(plugin).js
http://example.com/plugins/(plugin)/(additional resources)
http://example.com/about-(plugin)-plugin.json
```
To engage server-side plugins a site must serve:
```
ws://example.com/plugin/(plugin)
```
# Editing
To authenticate owners a site must:
```
(varies between sites)
```
To accept incremental changes a site must handle puts:
```
http://example.com/page/(slug)/action
```
To retrieve uncached content a site should serve:
```
http://example.com/slug.json?random=(random string)
```

**Comment by paul90** [comment]
The use of `?random=(random string)` is an affectation to ensure that the latest version of the file is retrieved. 

As long as the client/server correctly supports caching it is not really needed - it remains because some of the old versions of the server don't - the ruby version springs to mind.

**Comment by paul90** [comment]
In fact looking at the code, better cache support was only added to a test version of the node server :disappointed:

**Comment by WardCunningham** [comment]
We're now calling the small server case that @opn requests a "Foreign" server and have documented how that class of server can participate in the federation.

http://admin.asia.wiki.org/federating-foreign-servers.html

Here is an example of search-generated pages being served into the federation with modest additions to the search service. [example](https://github.com/WardCunningham/search/blob/82fa448f588de5a64404a4fb6e50b631ee8ee488/server.rb#L139-L154)
