### ISSUE TITLE
Local Changes is broken

### ISSUE THREAD

**Issue by opn** [fedwiki/wiki-client#165]
I'm having problems with Local Changes on my server. Here is the link and video:

- http://issues.fedwiki.org/view/issue-with-local-changes

What should I check for to track down the issue?

**Comment by WardCunningham** [comment]
Try refreshing your browser tab.
Check browser local storage with the inspector. 
Repeat test with previous wiki install.

**Comment by WardCunningham** [comment]
I notice that in one point in your video the activity plugin was offering `help`. It had correctly reported two local pages and then threw an error that generated the `help`. If you then opened up the inspector and pressed `retry` you would get additional diagnostic information.

## Debugging Changes

I'm guessing you somehow have non-page-json stored in local storage. I tried editing a page I didn't own and found things worked as expected. I examined the browser local storage which is visible on the resources tab. Here it shows page-json for the one locally edited page.

![image](https://cloud.githubusercontent.com/assets/12127/16174869/d15eb2b4-358c-11e6-95e4-43bda391c62c.png)

## Exporting Changes

You ask how to fork local changes to another site. The drag-and-drop doesn't work because local changes aren't visible to other sites.

You can retrieve your local changes in export format from a working Local Changes page. Double-click the Changes plugin which will open a dialog containing the export json. 

![image](https://cloud.githubusercontent.com/assets/12127/16175020/cb51820e-3594-11e6-87ce-4d31ab8451b3.png)

## Importing Changes

Here I have copied the export json and saved it in a local file, `export.json`, and dropped that into a browser tab for a site I own. This opens the import page from which you can open any page exported.

This process could be smoothed a bit but not a lot. The browser API does not allow much automation since this opens the door to spyware. Instead, the user must understand that they are writing a file and then importing it into another site.

![image](https://cloud.githubusercontent.com/assets/12127/16175026/2bcd914a-3595-11e6-9ff5-a0b18af62989.png)

**Comment by WardCunningham** [comment]
I've added an `Export Changes` button that will simplify this export-import strategy somewhat.
See https://github.com/fedwiki/wiki-plugin-changes/pull/7

![image](https://cloud.githubusercontent.com/assets/12127/16180050/a7d7ebd0-362d-11e6-8c78-132d505b6182.png)

**Comment by WardCunningham** [comment]
Fixed by https://github.com/fedwiki/wiki-plugin-changes/pull/7
