### ISSUE TITLE
new logic to delete pages from a site

### ISSUE THREAD

**Issue by WardCunningham** [fedwiki/wiki-client#196]
We haven't supported any mechanism for deleting server pages from the wiki client. With site adapters we now have machinery in place where we could conceivably support the review and retrieval of deleted pages, i.e. picking through the trash. In this issue I suggest the first step in this development, a mechanism for deleting pages in the first place.

One can now remove almost all of a page by retrieving the earliest version and forking that. The radically shortened page, an empty Story and one Action Journal, would irrevocably replace the previous content.

![image](https://cloud.githubusercontent.com/assets/12127/26155149/160b5300-3ac7-11e7-9f49-f7d3e4fd12cf.png)

From this screen, I am now suggesting, the fork button be interpreted to mean delete.

This would be a change from current behavior. Fork today would save this empty page as it appeared Tue Dec 29, 2015 after pressing the `create` button. The user experience I would prefer is to be set the view back to just before pressing `create`. With one server turnaround my ghost of the earliest revision becomes a ghost from one click earlier than that. 

![image](https://cloud.githubusercontent.com/assets/12127/26155732/1503aa46-3ac9-11e7-9269-dd7d9a1ce4a7.png)

This ghost page is sometimes called a Future page as it contains a Future plugin item offering to create a fully embodied page by several mechanisms. The page I have simulated by misspelling "Weather" might be called the Back to the Future page, or the Ghost of Page Past.

It is interesting to note that had the deleted page been created from a template then the Create Action we would have discarding would not have been empty. But, conveniently, our back to the future view offers to recreate from that template once again.

It is also possible that our back to the future page might notice that the just deleted page is still available in the "trash" and offer to retrieve it just as it will retrieve twins found in the neighborhood.

### Implementation

I am suggesting that we unwind new page creation, a reasonably complex asynchronous client-server interaction. Old page deletion will be similarly complex and asynchronous. Here is code.

https://github.com/fedwiki/wiki-client/blob/master/lib/legacy.coffee#L137-L152

The `.fork-page` click handler already does some case analysis while creating the action.
```
action = {type: 'fork'}
```
Here we could recognize the emptiness of a revision and create `{type: 'delete'}` instead. From there code flow would have to end up adjusting just about everything like the $page, pageObject and lineup. It would also have to prepare the client for the return from the pageHandler.put, what ever that is. The server-side implications are also vague.

https://github.com/fedwiki/wiki-server/blob/master/lib/server.coffee#L504-L590

The `app.put` handler already starts with a switch on the `action.type` so that is where its new flow would begin. The server has its own `pagehandler` which will need extension. An approach to saving deleted pages has to be worked out and then how this might appear to the client is also unknown. 

This mechanism was proposed two years ago as Fork Back to Creation. There is a short page in the goals pod on the subject. I'll cross-link this issue there.

http://ward.asia.wiki.org/fork-back-to-creation.html

**Comment by paul90** [comment]
Some thoughts...

"Fork Back to Creation" only ever provided a partial solution, in that it removed the page's content but not the page itself. So, it couldn't help resolve some of the problems caused by in inadvertent page forks. 

As discussed in this week's Hangout, rather than using the current page machinery, using a `put` with a `delete` action. It would be better to use a http `delete`, as allows the intention to be determined at a higher level within the page handler on the server.

On the client, when we retrieve the page's earliest version it would be a good idea to replace the fork icon with an alternative - how about &#9842; to make the intended action more explicit.

The idea is, I think, to move the page from the site into the site's recycler - so unlike "Fork Back to Creation" content should be recoverable, at least for a while. This is dependent on the development of a recycler site adapter, and how pages there are handled.

**Comment by WardCunningham** [comment]
We've taken the first steps with #197 which will issue http `delete` from the pageHandler as suggested. On going discussion continues there.
