### ISSUE TITLE
Content displays off edge of screen

### ISSUE THREAD

**Issue by hyperpape** [fedwiki/wiki-client#221]
I navigated to http://fed.wiki.org/view/welcome-visitors/view/about-federated-wiki/about.fed.wiki/neighborhoods using a 15" MacBook Pro, with Chrome as my browser. The content slightly overhangs the left edge of the screen, as shown in the attached screenshot. 
<img width="1440" alt="screen shot 2018-09-30 at 9 59 17 am" src="https://user-images.githubusercontent.com/1120101/46258403-fbe51400-c497-11e8-848f-446cad21e49a.png">

**Comment by WardCunningham** [comment]
I think this is a case of an almost match: the fixed width pages almost fit into the fixed width window and that it makes it look wrong.

If the browser were framed smaller on the display then you might see 2-1/4 pages and that would seem normal for pages that lineup and scroll left to right. 

We have a notion of an active window which has a faint shadow around it. Use the left/right arrow keys to move this selection. We will scroll the lineup so that the active window is fully visible. 

On my computer I can use cmd-plus/minus to enlarge or shrink the browser's window contents. This makes more or fewer pages fully visible.

**Comment by WardCunningham** [comment]
It is also possible to click a partially occluded page. This will choose it as the active page and scroll it fully into the browser's window.
