### ISSUE TITLE
Searching pages should survive reload

### ISSUE THREAD

**Issue by heymatthew** [fedwiki/wiki-client#283]
If I share a URL to a search page or reload a search page, the results get removed and I'm offered to create a new page instead.

Reproduction steps:
1. Navigate to http://ward.fed.wiki.org/view/welcome-visitors
2. Type "Ward" into the search box
3. See the search results
4. Refresh the page

What do I see?

![Screen Shot 2022-01-24 at 1 24 28 PM](https://user-images.githubusercontent.com/45738/150704471-435da3e0-ebe2-45d3-a2c8-f765bad427a4.png)

I expect instead to see my search results.

**Comment by heymatthew** [comment]
I don't mind having a crack at this, just give me some pointers and I'll get vimming <3

**Comment by paul90** [comment]
The search results page is a ghost page, so does not exist other than in your browser's memory. If you want to share it you should fork it into existence before sharing the URL.

**Comment by heymatthew** [comment]
Thank you for your suggestion @paul90, but maybe I should clarify the use case instead of saying this is an missing behaviour.

I would love to search Fed Wiki from my browser, but that means that URLs need to route to search results on page load.

Chrome and firefox let you do this. I set up @you in chrome, I'd open a search page by typing "@you search term" I go straight to search results.

![Screenshot 2022-11-25 at 12 57 27 PM](https://user-images.githubusercontent.com/45738/203876010-830d3f43-8f93-4116-aee3-f4af5a5f518a.png)

I set up @mdn as a shortcut in firefox, I'd open a search page by typing "@mdn search term" and it does the same.

![Screenshot 2022-11-25 at 12 47 21 PM](https://user-images.githubusercontent.com/45738/203875405-4d31094f-bca5-4198-8b35-64ad091fe0b1.png)

You can configure Chrome from chrome://settings/searchEngines and add a URL With `%s` to substitute your keyword.

![Screenshot 2022-11-25 at 12 40 05 PM](https://user-images.githubusercontent.com/45738/203874968-c6121499-69df-43cd-90b8-a97f13285236.png)

For Firefox you can add `%s` in the "keyword" field of bookmarks.

![Screenshot 2022-11-25 at 12 45 52 PM](https://user-images.githubusercontent.com/45738/203875308-37e427c6-8c0a-4f68-b36c-c908024c05a9.png)

If you use OpenSearch then browsers can pick this up automatically. [MDN Article](https://developer.mozilla.org/en-US/docs/Web/OpenSearch)

I really want to contribute to this project but I was discouraged by how quickly this issue was closed. I got the impression that this was so far away from the goals of the project that a PR wouldn't be helpful. This is also why it's taken me 10 months to come back.

However, this is a feature I depend on daily for my other workflows and I was really interested in making it available in this project too for me and for everyone.

As I said before, I don't mind having a crack at this but I want maintainers to want it too.

Would you reconsider this as a feature for FedWiki?

If so, could we reopen and discuss the approach?

**Comment by WardCunningham** [comment]
This issue began with an observation that ghost pages like search results to no survive reload. This is in fact true and is of little value to any user. It has occurred to us that we should not include ghost pages in the url because they are not available to the internet should that url be shared or reloaded.

Paul offers sound advice when he suggests that you save any ghost page you want to keep or share.

I gather from your subsequent comments that your issue is quite different and unrelated to search results surviving reload.

I think you are suggesting that if a federated wiki server performed the search function then there are shorthand mechanisms to engage that server behavior. This misunderstands how federated wiki search works at several levels.

I will explain search as it works for us. But first I concur that this issue is rightfully closed.

Federated wiki is unusual in that the client, the javascript loaded into your browser, browses any number of wiki servers simultaneously. It is not uncommon to see page counts in the many tens of thousands next to the search box in the web page footer. Browsing may have started at a site with a hundred pages but this number grows quickly as links reach out into the federation.

We implement search in the client javascript so that all of the tens of thousands of page are searched.

The tens of thousands of pages belong to the user who is doing the browsing. They are not a public resource and should not be made available to you.

**Comment by heymatthew** [comment]
Thanks for direction @WardCunningham and @paul90. I think you're right that I've miss-understood search. I can see now that search changes as I browse and this is a little surprising to me.

I would still love to contribute back in some way so you might see me leaving comments on other issues ❤️

**Comment by WardCunningham** [comment]
I have a server that offers some whole federation search capability.
I use it as a last resort when I have misplaced some page. 
It is stand-alone ruby code that shells out to grep.
It could be made faster and more friendly many ways.
I'd be happy to have help.
http://search.fed.wiki.org:3030/

<img width="759" alt="image" src="https://user-images.githubusercontent.com/12127/204169354-77263eda-6c9a-4e92-9cfd-1a34dfb89aff.png">

**Comment by heymatthew** [comment]
Thanks Ward, that looks like a good place to put energy. Is that the one hosted here:
https://github.com/WardCunningham/search

Is there already a wishlist?

**Comment by WardCunningham** [comment]
This is the top of the wishlist in my head. The word index started exploding in 2022. I believe this to be largely from the sudden popularity of posting links with very large base64 urls. The scraper foolishly scrapes that as words. Fixing this and then cleaning out the word index would make search fast enough that your shortcut would be useful.

<img width="741" alt="image" src="https://user-images.githubusercontent.com/12127/204685764-c8dea30f-6b22-4811-ad4c-c65d63bfe684.png">

The current index is downloadable. The stats of which the chart above are available online too. Details here:

http://ward.asia.wiki.org/view/search-index-downloads/view/sitemap-scrape-statistics

We often talk about a distributed implementation of search. I can imagine a scheme where there is some locality and some integration with our minisearch based full text search. Discussions begin in our lively chat room or privately by email:

https://app.element.io/#/room/#fedwiki:matrix.org
ward@c2.com
