### ISSUE TITLE
Journal changes that are story no-ops affect newer/older status

### ISSUE THREAD

**Issue by judell** [fedwiki/wiki-client#85]
If Mike forks Kate's page, then adds a factory, then a paragraph, then changes his mind and deletes the paragraph, he has not changed the story. But the page appears as newer. Kate will want to know why and will not easily be able to find out that in fact nothing she cares about has changed.

Should new/old status depend on the story only?

**Comment by WardCunningham** [comment]
This suggestion would be to consider the editDate of a page to be the most recent visible editorial change for an item that remains in the story. A data item that is updated as it is served or once rendered in the client would be responsible for its own chronology. This seems reasonable since we have already taken the first step towards what I will call 'algorithmic' dating.

The current approach in the client code dates back 26 days to pull request #72.

We changed the node server then realized the desired effect, detecting 'same', required a similar adjustment on the client. The same logic dates back to the ruby server which dated pages with the file mtime to an accuracy of seconds. Before that actions weren't dated. Many of these pages still exist.

Nothing of consequence should depend on the dates being accurate. Also, we're leaning toward non-chronological ordering of edits when merging journals. Long diverged pages render better if the related actions are kept together.

I stumbled across some logic that performed less well with forks ignored. Unfortunately I've forgotten what that was. I reasoned then that the sitemap should quote a second date, the lastTouchDate, if it is other than the editDate.
